language: swift
osx_image: xcode10.2
before_install:
- brew update
- brew install carthage || brew outdated carthage || brew upgrade carthage
install:
- carthage bootstrap
branches:
  only:
    - master
script:
  - set -o pipefail && xcodebuild build test -workspace Haneke.xcworkspace -scheme Haneke-iOS -destination 'platform=iOS Simulator,name=iPhone X,OS=12.0' | xcpretty --color
